### ISSUE TITLE
Cannot get scripts to work anymore

### ISSUE THREAD

**Issue by aarranshaw** [trmrsh/trm-doppler#3]
Hi Tom,

Getting back into using this software after a few years (I think since python 2 days?). However, the way one runs the scripts (`makemap.py` etc) seems to have changed and I cannot for the life of me figure out how to use them anymore.

For example, it used to be that I could just do `makemap.py -w test.cfg` on the command line to write out an example config, then I can use that config to make my starting maps. If I do that, or run `python makemap.py -w test.cfg` nothing happens - the script seems to run but I get no outputs. I don't even get an error if I don't put any arguments in. I try running it in ipython by importing `trm.doppler.scripts.makemap` and running `makemap('-w test.cfg')` but I get argparse errors so I fear I'm doing it wrong.

Could you please let me know what, if anything, I'm doing wrong? I know all the steps to get doppler maps but I can't seem to execute them!

Hope you are well,

Aarran

**Comment by aarranshaw** [comment]
If it makes a difference, I'm running anaconda python 3 on iMac with macOS 10.14 Mojave, but I don't think it's a platform issue, I think I'm simply executing the scripts wrong...

**Comment by trmrsh** [comment]
hi aarran, sorry for missing this. It should almost work as you have it. Here "makemap -w test" produces a file called "test.cfg" (NB there is no ".py" at the end). The first thing to see if things are working is "makemap -h" I would suggest. Let me know if that does not work for you.

**Comment by aarranshaw** [comment]
Aha, I definitely missed the part where installing trm-doppler populates `trm_software/bin` with executables linking to the python scripts. I will add that directory to my path. Thank you so much, I knew it would be a simple fix!
